import type { UILanguage } from "./mini-i18n";

const copy = {
	ru: {
		taglineTitle: "Ваши расходы рядом",
		taglineBody: "Откройте те же пространства, покупки и планы.",
		telegramEyebrow: "Без нового пароля",
		registerEyebrow: "Первый шаг",
		loginEyebrow: "С возвращением",
		telegramTitle: "Войти через Telegram",
		registerTitle: "Создать аккаунт",
		loginTitle: "Войти",
		methodLabel: "Способ входа",
		phone: "Телефон",
		email: "Почта",
		outsideRussia: "Я нахожусь за пределами России",
		inRussia: "Я нахожусь в России",
		telegramOutside: "Доступно пользователям за пределами России",
		phoneCodeTitle: "Введите последние 4 цифры",
		emailCodeTitle: "Введите код из письма",
		calling: "Звоним на ",
		sentTo: "Отправили на ",
		phoneCodeLabel: "Последние 4 цифры входящего номера",
		emailCodeLabel: "Код из 6 цифр",
		phoneExpired: "Срок подтверждения истёк. Запросите новый звонок.",
		emailExpired: "Срок действия кода истёк. Отправьте новый.",
		codeValid: (time: string) => `Код действует ещё ${time}`,
		checking: "Проверяем…",
		pasteCode: "Вставить код",
		retryAfter: (time: string) => `Снова через ${time}`,
		callAgain: "Позвонить ещё раз",
		sendAgain: "Отправить снова",
		changePhone: "Изменить номер",
		changeEmail: "Изменить почту",
		phoneHelp:
			"Отвечать не нужно. Запомните последние четыре цифры номера, с которого поступит звонок.",
		emailHelp: "Не нашли письмо? Проверьте папку «Спам».",
		name: "Имя",
		namePlaceholder: "Как к вам обращаться",
		consentPrefix: "Даю отдельное ",
		consentLink: "согласие на обработку персональных данных",
		requestingCall: "Запрашиваем звонок…",
		sending: "Отправляем…",
		callMe: "Позвонить мне",
		getCode: "Получить код",
		registerPhoneHint:
			"Пароль не нужен — подтвердите номер по входящему звонку.",
		registerEmailHint: "Пароль не нужен — вход подтверждается кодом из письма.",
		loginPhoneHint: "Введите номер, указанный при регистрации или в профиле.",
		loginEmailHint: "Введите почту, указанную при регистрации или в профиле.",
		alreadyAccount: "Уже есть аккаунт?",
		noAccount: "Ещё нет аккаунта?",
		create: "Создать",
		offer: "Оферта",
		privacy: "Конфиденциальность",
		dataProcessing: "Обработка данных",
		refunds: "Возвраты",
		installTitle: "Добавьте приложение на экран",
		installBody: "Открывайте расходы одним касанием.",
		install: "Установить",
		instruction: "Инструкция",
		failedCall: "Не удалось запустить проверочный звонок",
		failedSend: "Не удалось отправить код",
		emailRegistered: "Эта почта уже зарегистрирована. Выберите «Войти».",
		callFailed:
			"Не удалось запустить звонок. Проверьте номер или войдите по почте.",
		callWait: "Звонок уже запрошен. Новый можно запросить через минуту.",
		codeWait: "Код уже отправлен. Новый можно запросить через минуту.",
		hourlyCall: "Вы уже запросили 3 звонка за последний час. Попробуйте позже.",
		hourlyCode: "Вы уже запросили 3 кода за последний час. Попробуйте позже.",
		dailyCall: "Суточный лимит звонков исчерпан. Попробуйте завтра.",
		dailyCode: "Суточный лимит кодов исчерпан. Попробуйте завтра.",
		tooMany: "Слишком много попыток. Подождите и попробуйте снова.",
		invalidCode: "Неверный код или срок его действия истёк.",
		clipboardMissing: (length: number) => `В буфере нет кода из ${length} цифр`,
		codePasted: "Код вставлен",
		pasteManually: "Зажмите поле и выберите «Вставить»",
	},
	en: {
		taglineTitle: "Your spending, close at hand",
		taglineBody: "Open the same spaces, purchases, and plans.",
		telegramEyebrow: "No new password",
		registerEyebrow: "First step",
		loginEyebrow: "Welcome back",
		telegramTitle: "Continue with Telegram",
		registerTitle: "Create an account",
		loginTitle: "Sign in",
		methodLabel: "Sign-in method",
		phone: "Phone",
		email: "Email",
		outsideRussia: "I am outside Russia",
		inRussia: "I am in Russia",
		telegramOutside: "Available to users outside Russia",
		phoneCodeTitle: "Enter the last 4 digits",
		emailCodeTitle: "Enter the code from the email",
		calling: "Calling ",
		sentTo: "Sent to ",
		phoneCodeLabel: "Last 4 digits of the incoming number",
		emailCodeLabel: "6-digit code",
		phoneExpired: "Confirmation expired. Request another call.",
		emailExpired: "The code has expired. Request a new one.",
		codeValid: (time: string) => `Code valid for ${time}`,
		checking: "Checking…",
		pasteCode: "Paste code",
		retryAfter: (time: string) => `Try again in ${time}`,
		callAgain: "Call again",
		sendAgain: "Send again",
		changePhone: "Change phone number",
		changeEmail: "Change email",
		phoneHelp:
			"You do not need to answer. Remember the last four digits of the incoming number.",
		emailHelp: "Cannot find the email? Check your spam folder.",
		name: "Name",
		namePlaceholder: "What should we call you?",
		consentPrefix: "I give separate ",
		consentLink: "consent to personal data processing",
		requestingCall: "Requesting a call…",
		sending: "Sending…",
		callMe: "Call me",
		getCode: "Get code",
		registerPhoneHint:
			"No password needed — confirm your number by an incoming call.",
		registerEmailHint:
			"No password needed — sign in with a code from the email.",
		loginPhoneHint:
			"Enter the phone number used during registration or in your profile.",
		loginEmailHint:
			"Enter the email used during registration or in your profile.",
		alreadyAccount: "Already have an account?",
		noAccount: "No account yet?",
		create: "Create",
		offer: "Terms",
		privacy: "Privacy",
		dataProcessing: "Data processing",
		refunds: "Refunds",
		installTitle: "Add the app to your home screen",
		installBody: "Open your expenses with one tap.",
		install: "Install",
		instruction: "Instructions",
		failedCall: "Could not start the verification call",
		failedSend: "Could not send the code",
		emailRegistered: "This email is already registered. Choose “Sign in”.",
		callFailed:
			"Could not start the call. Check the number or sign in by email.",
		callWait: "A call was already requested. Try again in one minute.",
		codeWait: "A code was already sent. Try again in one minute.",
		hourlyCall: "You have requested 3 calls in the last hour. Try again later.",
		hourlyCode: "You have requested 3 codes in the last hour. Try again later.",
		dailyCall: "The daily call limit has been reached. Try again tomorrow.",
		dailyCode: "The daily code limit has been reached. Try again tomorrow.",
		tooMany: "Too many attempts. Wait and try again.",
		invalidCode: "The code is invalid or has expired.",
		clipboardMissing: (length: number) =>
			`The clipboard does not contain a ${length}-digit code`,
		codePasted: "Code pasted",
		pasteManually: "Press and hold the field, then choose Paste",
	},
	es: {
		taglineTitle: "Tus gastos, siempre a mano",
		taglineBody: "Abre los mismos espacios, compras y planes.",
		telegramEyebrow: "Sin contraseña nueva",
		registerEyebrow: "Primer paso",
		loginEyebrow: "Te damos la bienvenida",
		telegramTitle: "Continuar con Telegram",
		registerTitle: "Crear una cuenta",
		loginTitle: "Iniciar sesión",
		methodLabel: "Método de acceso",
		phone: "Teléfono",
		email: "Correo",
		outsideRussia: "Estoy fuera de Rusia",
		inRussia: "Estoy en Rusia",
		telegramOutside: "Disponible para usuarios fuera de Rusia",
		phoneCodeTitle: "Introduce los últimos 4 dígitos",
		emailCodeTitle: "Introduce el código del correo",
		calling: "Llamando al ",
		sentTo: "Enviado a ",
		phoneCodeLabel: "Últimos 4 dígitos del número entrante",
		emailCodeLabel: "Código de 6 dígitos",
		phoneExpired: "La confirmación ha caducado. Solicita otra llamada.",
		emailExpired: "El código ha caducado. Solicita uno nuevo.",
		codeValid: (time: string) => `Código válido durante ${time}`,
		checking: "Comprobando…",
		pasteCode: "Pegar código",
		retryAfter: (time: string) => `Reintentar en ${time}`,
		callAgain: "Llamar de nuevo",
		sendAgain: "Enviar de nuevo",
		changePhone: "Cambiar teléfono",
		changeEmail: "Cambiar correo",
		phoneHelp:
			"No hace falta responder. Recuerda los últimos cuatro dígitos del número entrante.",
		emailHelp: "¿No encuentras el correo? Revisa la carpeta de spam.",
		name: "Nombre",
		namePlaceholder: "¿Cómo debemos llamarte?",
		consentPrefix: "Doy mi ",
		consentLink: "consentimiento para el tratamiento de datos personales",
		requestingCall: "Solicitando llamada…",
		sending: "Enviando…",
		callMe: "Llamarme",
		getCode: "Obtener código",
		registerPhoneHint:
			"No necesitas contraseña: confirma el número mediante una llamada.",
		registerEmailHint:
			"No necesitas contraseña: accede con el código del correo.",
		loginPhoneHint:
			"Introduce el teléfono usado al registrarte o en tu perfil.",
		loginEmailHint: "Introduce el correo usado al registrarte o en tu perfil.",
		alreadyAccount: "¿Ya tienes una cuenta?",
		noAccount: "¿Aún no tienes una cuenta?",
		create: "Crear",
		offer: "Condiciones",
		privacy: "Privacidad",
		dataProcessing: "Tratamiento de datos",
		refunds: "Reembolsos",
		installTitle: "Añade la aplicación a la pantalla de inicio",
		installBody: "Abre tus gastos con un toque.",
		install: "Instalar",
		instruction: "Instrucciones",
		failedCall: "No se pudo iniciar la llamada de verificación",
		failedSend: "No se pudo enviar el código",
		emailRegistered: "Este correo ya está registrado. Elige «Iniciar sesión».",
		callFailed:
			"No se pudo iniciar la llamada. Revisa el número o accede por correo.",
		callWait: "Ya se solicitó una llamada. Inténtalo de nuevo en un minuto.",
		codeWait: "Ya se envió un código. Inténtalo de nuevo en un minuto.",
		hourlyCall:
			"Ya has solicitado 3 llamadas en la última hora. Inténtalo más tarde.",
		hourlyCode:
			"Ya has solicitado 3 códigos en la última hora. Inténtalo más tarde.",
		dailyCall: "Se alcanzó el límite diario de llamadas. Inténtalo mañana.",
		dailyCode: "Se alcanzó el límite diario de códigos. Inténtalo mañana.",
		tooMany: "Demasiados intentos. Espera e inténtalo de nuevo.",
		invalidCode: "El código no es válido o ha caducado.",
		clipboardMissing: (length: number) =>
			`El portapapeles no contiene un código de ${length} dígitos`,
		codePasted: "Código pegado",
		pasteManually: "Mantén pulsado el campo y elige Pegar",
	},
} as const;

export const browserAuthCopy = (language: UILanguage) => copy[language];
