import type { UILanguage } from "./mini-i18n";

const copy = {
	ru: {
		taglineTitle: "Ваши расходы рядом",
		taglineBody: "Откройте те же пространства, покупки и планы.",
		telegramEyebrow: "Без нового пароля",
		registerEyebrow: "Первый шаг",
		loginEyebrow: "С возвращением",
		telegramTitle: "Войти через Telegram",
		registerTitle: "Создать аккаунт",
		loginTitle: "Войти",
		methodLabel: "Способ входа",
		phone: "Телефон",
		email: "Почта",
		outsideRussia: "Я нахожусь за пределами России",
		inRussia: "Я нахожусь в России",
		telegramOutside: "Доступно пользователям за пределами России",
		phoneCodeTitle: "Подтвердите номер звонком",
		emailCodeTitle: "Введите код из письма",
		calling: "Проверяем ",
		sentTo: "Отправили на ",
		emailCodeLabel: "Код из 6 цифр",
		phoneExpired: "Время подтверждения истекло. Получите новый номер.",
		emailExpired: "Срок действия кода истёк. Отправьте новый.",
		callValid: (time: string) => `Позвонить можно ещё ${time}`,
		codeValid: (time: string) => `Код действует ещё ${time}`,
		checking: "Проверяем…",
		pasteCode: "Вставить код",
		retryAfter: (time: string) => `Снова через ${time}`,
		callAgain: "Получить новый номер",
		sendAgain: "Отправить снова",
		changePhone: "Изменить номер",
		changeEmail: "Изменить почту",
		phoneHelp: "Звонок автоматически сбросится и останется бесплатным.",
		callAction: "Позвоните с указанного выше телефона для подтверждения",
		waitingForCall: "Ждём ваш звонок…",
		emailHelp: "Не нашли письмо? Проверьте папку «Спам».",
		name: "Имя",
		namePlaceholder: "Как к вам обращаться",
		consentPrefix: "Даю отдельное ",
		consentLink: "согласие на обработку персональных данных",
		requestingCall: "Готовим номер…",
		sending: "Отправляем…",
		callMe: "Получить номер",
		getCode: "Получить код",
		registerPhoneHint:
			"Пароль не нужен — позвоните на бесплатный номер для подтверждения.",
		registerEmailHint: "Пароль не нужен — вход подтверждается кодом из письма.",
		loginPhoneHint: "Введите номер, указанный при регистрации или в профиле.",
		loginEmailHint: "Введите почту, указанную при регистрации или в профиле.",
		alreadyAccount: "Уже есть аккаунт?",
		noAccount: "Ещё нет аккаунта?",
		create: "Создать",
		offer: "Оферта",
		privacy: "Конфиденциальность",
		dataProcessing: "Обработка данных",
		refunds: "Возвраты",
		installTitle: "Добавьте приложение на экран",
		installBody: "Открывайте расходы одним касанием.",
		install: "Установить",
		instruction: "Инструкция",
		installedNotice: "Приложение добавлено на главный экран",
		confirmInstallNotice: "Подтвердите добавление приложения на главный экран",
		installGuideTitle: "Добавить на главный экран",
		installGuideBody:
			"Приложение откроется отдельным окном и будет доступно как обычная иконка.",
		installGuideDone: "Понятно",
		installGuideIOS: [
			"Откройте эту страницу в Safari.",
			"Нажмите «Поделиться» в панели браузера.",
			"Выберите «На экран Домой», затем «Добавить».",
		],
		installGuideAndroid: [
			"Откройте меню браузера ⋮.",
			"Выберите «Установить приложение» или «Добавить на главный экран».",
			"Подтвердите установку.",
		],
		installGuideDesktop: [
			"Откройте меню браузера.",
			"Выберите «Установить Пока не забыл».",
			"Подтвердите установку приложения.",
		],
		failedCall: "Не удалось запустить проверочный звонок",
		failedSend: "Не удалось отправить код",
		emailRegistered: "Эта почта уже зарегистрирована. Выберите «Войти».",
		callFailed:
			"Не удалось запустить звонок. Проверьте номер или войдите по почте.",
		callWait: "Звонок уже запрошен. Новый можно запросить через минуту.",
		codeWait: "Код уже отправлен. Новый можно запросить через минуту.",
		hourlyCall: "Вы уже запросили 3 звонка за последний час. Попробуйте позже.",
		hourlyCode: "Вы уже запросили 3 кода за последний час. Попробуйте позже.",
		dailyCall: "Суточный лимит звонков исчерпан. Попробуйте завтра.",
		dailyCode: "Суточный лимит кодов исчерпан. Попробуйте завтра.",
		tooMany: "Слишком много попыток. Подождите и попробуйте снова.",
		invalidCode: "Неверный код или срок его действия истёк.",
		clipboardMissing: (length: number) => `В буфере нет кода из ${length} цифр`,
		codePasted: "Код вставлен",
		pasteManually: "Зажмите поле и выберите «Вставить»",
	},
	en: {
		taglineTitle: "Your spending, close at hand",
		taglineBody: "Open the same spaces, purchases, and plans.",
		telegramEyebrow: "No new password",
		registerEyebrow: "First step",
		loginEyebrow: "Welcome back",
		telegramTitle: "Continue with Telegram",
		registerTitle: "Create an account",
		loginTitle: "Sign in",
		methodLabel: "Sign-in method",
		phone: "Phone",
		email: "Email",
		outsideRussia: "I am outside Russia",
		inRussia: "I am in Russia",
		telegramOutside: "Available to users outside Russia",
		phoneCodeTitle: "Confirm your phone by calling",
		emailCodeTitle: "Enter the code from the email",
		calling: "Verifying ",
		sentTo: "Sent to ",
		emailCodeLabel: "6-digit code",
		phoneExpired: "Confirmation expired. Request a new number.",
		emailExpired: "The code has expired. Request a new one.",
		callValid: (time: string) => `Call within ${time}`,
		codeValid: (time: string) => `Code valid for ${time}`,
		checking: "Checking…",
		pasteCode: "Paste code",
		retryAfter: (time: string) => `Try again in ${time}`,
		callAgain: "Get a new number",
		sendAgain: "Send again",
		changePhone: "Change phone number",
		changeEmail: "Change email",
		phoneHelp: "The call will be rejected automatically and remain free.",
		callAction: "Call this number from the phone shown above to confirm",
		waitingForCall: "Waiting for your call…",
		emailHelp: "Cannot find the email? Check your spam folder.",
		name: "Name",
		namePlaceholder: "What should we call you?",
		consentPrefix: "I give separate ",
		consentLink: "consent to personal data processing",
		requestingCall: "Preparing a number…",
		sending: "Sending…",
		callMe: "Get call number",
		getCode: "Get code",
		registerPhoneHint:
			"No password needed — call a free number to confirm your phone.",
		registerEmailHint:
			"No password needed — sign in with a code from the email.",
		loginPhoneHint:
			"Enter the phone number used during registration or in your profile.",
		loginEmailHint:
			"Enter the email used during registration or in your profile.",
		alreadyAccount: "Already have an account?",
		noAccount: "No account yet?",
		create: "Create",
		offer: "Terms",
		privacy: "Privacy",
		dataProcessing: "Data processing",
		refunds: "Refunds",
		installTitle: "Add the app to your home screen",
		installBody: "Open your expenses with one tap.",
		install: "Install",
		instruction: "Instructions",
		installedNotice: "The app was added to your home screen",
		confirmInstallNotice: "Confirm adding the app to your home screen",
		installGuideTitle: "Add to home screen",
		installGuideBody:
			"The app will open in its own window and be available like a regular app icon.",
		installGuideDone: "Got it",
		installGuideIOS: [
			"Open this page in Safari.",
			"Tap Share in the browser toolbar.",
			"Choose Add to Home Screen, then tap Add.",
		],
		installGuideAndroid: [
			"Open the browser menu ⋮.",
			"Choose Install app or Add to Home screen.",
			"Confirm the installation.",
		],
		installGuideDesktop: [
			"Open the browser menu.",
			"Choose Install Poka ne zabyl.",
			"Confirm the app installation.",
		],
		failedCall: "Could not start the verification call",
		failedSend: "Could not send the code",
		emailRegistered: "This email is already registered. Choose “Sign in”.",
		callFailed:
			"Could not start the call. Check the number or sign in by email.",
		callWait: "A call was already requested. Try again in one minute.",
		codeWait: "A code was already sent. Try again in one minute.",
		hourlyCall: "You have requested 3 calls in the last hour. Try again later.",
		hourlyCode: "You have requested 3 codes in the last hour. Try again later.",
		dailyCall: "The daily call limit has been reached. Try again tomorrow.",
		dailyCode: "The daily code limit has been reached. Try again tomorrow.",
		tooMany: "Too many attempts. Wait and try again.",
		invalidCode: "The code is invalid or has expired.",
		clipboardMissing: (length: number) =>
			`The clipboard does not contain a ${length}-digit code`,
		codePasted: "Code pasted",
		pasteManually: "Press and hold the field, then choose Paste",
	},
	es: {
		taglineTitle: "Tus gastos, siempre a mano",
		taglineBody: "Abre los mismos espacios, compras y planes.",
		telegramEyebrow: "Sin contraseña nueva",
		registerEyebrow: "Primer paso",
		loginEyebrow: "Te damos la bienvenida",
		telegramTitle: "Continuar con Telegram",
		registerTitle: "Crear una cuenta",
		loginTitle: "Iniciar sesión",
		methodLabel: "Método de acceso",
		phone: "Teléfono",
		email: "Correo",
		outsideRussia: "Estoy fuera de Rusia",
		inRussia: "Estoy en Rusia",
		telegramOutside: "Disponible para usuarios fuera de Rusia",
		phoneCodeTitle: "Confirma tu teléfono con una llamada",
		emailCodeTitle: "Introduce el código del correo",
		calling: "Verificando ",
		sentTo: "Enviado a ",
		emailCodeLabel: "Código de 6 dígitos",
		phoneExpired: "La confirmación ha caducado. Solicita otro número.",
		emailExpired: "El código ha caducado. Solicita uno nuevo.",
		callValid: (time: string) => `Llama en ${time}`,
		codeValid: (time: string) => `Código válido durante ${time}`,
		checking: "Comprobando…",
		pasteCode: "Pegar código",
		retryAfter: (time: string) => `Reintentar en ${time}`,
		callAgain: "Obtener otro número",
		sendAgain: "Enviar de nuevo",
		changePhone: "Cambiar teléfono",
		changeEmail: "Cambiar correo",
		phoneHelp: "La llamada se rechazará automáticamente y será gratuita.",
		callAction: "Llama a este número desde el teléfono indicado para confirmar",
		waitingForCall: "Esperando tu llamada…",
		emailHelp: "¿No encuentras el correo? Revisa la carpeta de spam.",
		name: "Nombre",
		namePlaceholder: "¿Cómo debemos llamarte?",
		consentPrefix: "Doy mi ",
		consentLink: "consentimiento para el tratamiento de datos personales",
		requestingCall: "Preparando un número…",
		sending: "Enviando…",
		callMe: "Obtener número",
		getCode: "Obtener código",
		registerPhoneHint:
			"No necesitas contraseña: llama gratis para confirmar tu teléfono.",
		registerEmailHint:
			"No necesitas contraseña: accede con el código del correo.",
		loginPhoneHint:
			"Introduce el teléfono usado al registrarte o en tu perfil.",
		loginEmailHint: "Introduce el correo usado al registrarte o en tu perfil.",
		alreadyAccount: "¿Ya tienes una cuenta?",
		noAccount: "¿Aún no tienes una cuenta?",
		create: "Crear",
		offer: "Condiciones",
		privacy: "Privacidad",
		dataProcessing: "Tratamiento de datos",
		refunds: "Reembolsos",
		installTitle: "Añade la aplicación a la pantalla de inicio",
		installBody: "Abre tus gastos con un toque.",
		install: "Instalar",
		instruction: "Instrucciones",
		installedNotice: "La aplicación se añadió a la pantalla de inicio",
		confirmInstallNotice:
			"Confirma que quieres añadir la aplicación a la pantalla de inicio",
		installGuideTitle: "Añadir a la pantalla de inicio",
		installGuideBody:
			"La aplicación se abrirá en su propia ventana y estará disponible como un icono normal.",
		installGuideDone: "Entendido",
		installGuideIOS: [
			"Abre esta página en Safari.",
			"Pulsa Compartir en la barra del navegador.",
			"Elige Añadir a la pantalla de inicio y después Añadir.",
		],
		installGuideAndroid: [
			"Abre el menú del navegador ⋮.",
			"Elige Instalar aplicación o Añadir a la pantalla de inicio.",
			"Confirma la instalación.",
		],
		installGuideDesktop: [
			"Abre el menú del navegador.",
			"Elige Instalar Poka ne zabyl.",
			"Confirma la instalación de la aplicación.",
		],
		failedCall: "No se pudo iniciar la llamada de verificación",
		failedSend: "No se pudo enviar el código",
		emailRegistered: "Este correo ya está registrado. Elige «Iniciar sesión».",
		callFailed:
			"No se pudo iniciar la llamada. Revisa el número o accede por correo.",
		callWait: "Ya se solicitó una llamada. Inténtalo de nuevo en un minuto.",
		codeWait: "Ya se envió un código. Inténtalo de nuevo en un minuto.",
		hourlyCall:
			"Ya has solicitado 3 llamadas en la última hora. Inténtalo más tarde.",
		hourlyCode:
			"Ya has solicitado 3 códigos en la última hora. Inténtalo más tarde.",
		dailyCall: "Se alcanzó el límite diario de llamadas. Inténtalo mañana.",
		dailyCode: "Se alcanzó el límite diario de códigos. Inténtalo mañana.",
		tooMany: "Demasiados intentos. Espera e inténtalo de nuevo.",
		invalidCode: "El código no es válido o ha caducado.",
		clipboardMissing: (length: number) =>
			`El portapapeles no contiene un código de ${length} dígitos`,
		codePasted: "Código pegado",
		pasteManually: "Mantén pulsado el campo y elige Pegar",
	},
} as const;

export const browserAuthCopy = (language: UILanguage) => copy[language];
