import {
	AirplaneTilt,
	Armchair,
	Baby,
	Bank,
	Barbell,
	Basket,
	Bed,
	Briefcase,
	Broom,
	Buildings,
	Camera,
	Car,
	Coffee,
	Desktop,
	DeviceMobile,
	DotsThreeCircle,
	Drop,
	FilmSlate,
	FirstAid,
	ForkKnife,
	Garage,
	GasPump,
	Gift,
	GraduationCap,
	GridFour,
	Hammer,
	HardHat,
	HouseLine,
	type Icon,
	Lightning,
	Megaphone,
	Package,
	PaintBrush,
	Palette,
	PawPrint,
	Pill,
	Plant,
	Repeat,
	ShieldCheck,
	Sparkle,
	Stack,
	TShirt,
	Tag,
	Taxi,
	Ticket,
	Toolbox,
	Truck,
	UsersThree,
	Warehouse,
	WashingMachine,
	WifiHigh,
	Wine,
	Wrench,
} from "@phosphor-icons/react";
import {
	type CategoryIconKey,
	categoryIconOption,
	normalizeCategoryIconKey,
	suggestCategoryIconKey,
} from "./category-icon-catalog";

const categoryIcons: Record<CategoryIconKey, Icon> = {
	alcohol: Wine,
	appliances: WashingMachine,
	beauty: Sparkle,
	business: Briefcase,
	children: Baby,
	cleaning: Broom,
	clothing: TShirt,
	coffee: Coffee,
	computer: Desktop,
	construction: HardHat,
	delivery: Truck,
	dining: ForkKnife,
	education: GraduationCap,
	electronics: DeviceMobile,
	electricity: Lightning,
	finance: Bank,
	flooring: GridFour,
	fuel: GasPump,
	furniture: Armchair,
	garden: Plant,
	gifts: Gift,
	groceries: Basket,
	health: FirstAid,
	hobbies: Palette,
	home: Hammer,
	hotel: Bed,
	housing: HouseLine,
	insurance: ShieldCheck,
	internet: WifiHigh,
	leisure: FilmSlate,
	marketing: Megaphone,
	materials: Stack,
	office: Buildings,
	packaging: Package,
	paint: PaintBrush,
	parking: Garage,
	pets: PawPrint,
	pharmacy: Pill,
	photo: Camera,
	plumbing: Drop,
	repair: Wrench,
	sports: Barbell,
	subscriptions: Repeat,
	tag: Tag,
	taxi: Taxi,
	team: UsersThree,
	tickets: Ticket,
	tools: Toolbox,
	transport: Car,
	travel: AirplaneTilt,
	warehouse: Warehouse,
};

export const CategoryIcon = ({
	iconKey,
	categoryKey,
	name,
	size = 20,
	weight = "bold",
}: {
	iconKey?: string | null;
	categoryKey?: string;
	name?: string;
	size?: number;
	weight?: "regular" | "bold" | "fill";
}) => {
	const resolvedKey = iconKey
		? normalizeCategoryIconKey(iconKey)
		: suggestCategoryIconKey(name || "", categoryKey || "");
	const IconComponent = categoryIcons[resolvedKey] || DotsThreeCircle;
	return <IconComponent size={size} weight={weight} aria-hidden="true" />;
};

export const categoryIconTone = (iconKey?: string | null) =>
	categoryIconOption(iconKey).tone;
