#!/bin/sh
if command -v pwsh.exe >/dev/null 2>&1; then
  pwsh.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ./scripts/precommit-client.ps1
else
  powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ./scripts/precommit-client.ps1
fi
